.\" Manpage for jami-gnome.
.TH man 8 "08 April 2016" "1.0" "jami-gnome man page"
.SH NAME
jami-gnome \- Gnome client for jami.net
.SH SYNOPSIS
jami-gnome [options]
.SH DESCRIPTION
jami-gnome is a gnome client for jami.net
.SH OPTIONS
.B \-v, \-\-version
Display the version and exit.
.TP
.B \-d, \-\-debug
Enable debug.
.TP
.B \-r, \-\-restore-last-window-state
Restores the hidden state of the main window. This is only applicable to the primary instance.
.TP
.B \-h, \-\-help
Display help text and exit.
.SH SEE ALSO
jamid(1)
.SH AUTHOR
Alexandre Viau (alexandre.viau@savoirfairelinux.net)
