.\" Manpage for ring-gnome.
.TH man 8 "08 April 2016" "1.0" "ring-gnome man page"
.SH NAME
ring-gnome \- Gnome client for Ring.cx
.SH SYNOPSIS
ring-gnome [options]
.SH DESCRIPTION
ring-gnome is a gnome client for Ring.cx
.SH OPTIONS
.B \-v, \-\-version
Display the version and exit.
.TP
.B \-d, \-\-debug
Enable debug.
.TP
.B \-r, \-\-restore-last-window-state
Restores the hidden state of the main window. This is only applicable to the primary instance.
.TP
.B \-h, \-\-help
Display help text and exit.
.SH SEE ALSO
dring(1)
.SH AUTHOR
Alexandre Viau (alexandre.viau@savoirfairelinux.net)
