FROM fedora:21

RUN yum upgrade -y
RUN yum install rpm-build tar rsync git make autoconf automake cmake libtool dbus-devel pcre-devel yaml-cpp-devel gcc-c++ \
    boost-devel dbus-c++-devel dbus-devel libupnp-devel qt5-qtbase-devel \
    gnome-icon-theme-symbolic chrpath check astyle gnutls-devel yasm git \
    cmake clutter-gtk-devel clutter-devel glib2-devel gtk3-devel evolution-data-server-devel \
    libnotify-devel -y
